create table permissions
(
    permission_name varchar(255) not null,
    role_role_name  varchar(255) not null,
    primary key (role_role_name, permission_name)
);
create table persons
(
    age            int4         not null,
    name           varchar(255) not null,
    surname        varchar(255) not null,
    city_of_living varchar(255),
    phone_number   varchar(255),
    primary key (age, name, surname)
);
create table roles
(
    role_name varchar(255) not null,
    primary key (role_name)
);
create table user_roles
(
    id                   int4 generated by default as identity,
    custom_user_username varchar(255),
    role_role_name       varchar(255),
    primary key (id)
);
create table users
(
    username varchar(255) not null,
    password varchar(255) not null,
    primary key (username)
);
alter table if exists permissions
    add constraint FK4r8l4uxsgpv18gc8cb1mxx2ka foreign key (role_role_name) references roles;
alter table if exists user_roles
    add constraint FKjg58nxyo9mxh1x0fr6rqsjcuy foreign key (custom_user_username) references users;
alter table if exists user_roles
    add constraint FKndmrfh93qxb0sq6nkuksh7rwd foreign key (role_role_name) references roles;
